---
title: "git_00"
author: "Sylvia Rodriguez"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves
      Did gyre and gimble in the wabe:
All mimsy were the borogoves,
      And the mome raths outgrabe.

“Beware the Jabberwock, my son!

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire, 
Some say in ice. 
From what I’ve tasted of desire 
I hold with those who favor fire. 

But if it had to perish twice,


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea, 
Shining with all his might: 
He did his very best to make 
The billows smooth and bright — 
And this was odd, because it was 
The middle of the night. 

The moon was shining sulkily, 
Because she thought the sun Had got no business to be there 
After the day was done — 
"It's very rude of him," she said, 
"To come and spoil the fun."

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

If you think you are beaten, you are;
If you think you dare not, you don’t;
If you’d like to win, but think you can’t,
It’s almost a cinch you won’t.
If you think you’ll lose, you’re lost,
For out in the word we find
Success begins with a fellow’s will,
It’s all in the state of mind.

If you think you’re outcasted, you are;
You’ve got to think high to rise.
You’ve got to be sure of yourself before
You can ever win a prize.
Life’s battles don’t always go
To the stronger or faster man;
But soon or late the man who wins
Is the man who thinks he can.
